# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'
info:
  title: smsService API
  description: Send and receive SMS with smsService API
  version: "0.0.1"
  termsOfService: http://api.lineberty.net/terms/
  contact:
    name: API Support
    url: http://www.lineberty.net/support
    email: support@lineberty.net
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

host: "localhost:8082"
#host: "http://api.lineberty.net/"

schemes:
  - http
  # - https

basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json

paths:
  /send:
    post:
      tags:
        - sms
        - subscription
      summary: Send SMS to the phone number and subscribe to get the receiver response
      description: ""
      operationId: sendSms
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: The authorization token
          required: true
          type: string
        - in: body
          name: body
          description: informations needed to send the sms
          required: true
          schema:
            $ref: "#/definitions/sendSmsRequest"
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid parameters supplied
        "401":
          description: Wrong parameters
  /subscribe:
    post:
      tags:
        - subscription
      summary: Subscribe to get the receiver response
      description: ""
      operationId: subscribe
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: The authorization token
          required: true
          type: string
        - in: body
          name: body
          description: informations needed to subscribe
          required: true
          schema:
            $ref: "#/definitions/subscribeRequest"
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid parameters supplied
        "401":
          description: Wrong parameters
  /unsubscribe:
    post:
      tags:
        - subscription
      summary: Unsubscribe to get a response from a phone
      description: ""
      operationId: unsubscribe
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: The authorization token
          required: true
          type: string
        - in: body
          name: body
          description: informations needed to unsubscribe
          required: true
          schema:
            $ref: "#/definitions/unsubscribeRequest"
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid parameters supplied
        "401":
          description: Wrong parameters
definitions:
  sendSmsRequest:
    required:
      - phone
      - msg
    properties:
      phone:
        type: string
        pattern: '^00[0-9]{1,3}[0-9]{7,14}$'
      msg:
        type: string
  subscribeRequest:
    required:
      - phone
      - serviceUrl
      - callbackPath
      - description
    properties:
      phone:
        type: string
        pattern: '^00[0-9]{1,3}[0-9]{7,14}$'
      serviceUrl:
        type: string
      callbackPath:
        type: string
      description:
        type: string
      lang:
        type: string
  unsubscribeRequest:
    required:
      - phone
      - serviceUrl
    properties:
      phone:
        type: string
        pattern: '^00[0-9]{1,3}[0-9]{7,14}$'
      serviceUrl:
        type: string
